### ISSUE TITLE
Edit label on already executed test

### ISSUE THREAD

**Issue by vyskoczilova** [WPO-Foundation/webpagetest#1768] opened 2022-02-24 18:11 UTC
## Feature Request Summary
Allow editing label from the already executed test for logged-in user.

### What's the motivation or use case for the change/feature?
I want to re-run the test with the same settings but update the label with the latest release number or any other custom note, but it doesn't seem to be possible (or is it hidden?).

**Comment by tkadlec** [comment] 2022-03-03 15:25
Duplicate of #1674

We definitely want to add this and it's on the roadmap! Stay tuned. :)

**Closed by tkadlec** 2022-03-03 15:25 UTC
Labels: Type: Enhancement
