### ISSUE TITLE
Part of the page disappears as you scroll

### ISSUE THREAD

**Issue by kevinfarrugia** [WPO-Foundation/webpagetest#2533] opened 2022-11-11 10:26 UTC
## Description
When scrolling downwards on devices with a large viewport (1920 and upwards), as you scoll parts of the page get covered by a white area. This usually overlaps the requests table or the custom metrics if you have many.

### Steps to reproduce
- Browser: Google Chrome
- OS: Ubuntu 22.04

Steps:
- Go to: https://www.webpagetest.org/result/221111_AiDc1Y_64P/1/details/#waterfall_view_step1 using a device with a large viewport (in my case 1920w)
- Scroll downards, notice how the table gets covered by a white area. (see attached video)

https://user-images.githubusercontent.com/8075326/201320999-0842ec80-76fb-4817-b2a2-45c66d02e7f4.mp4

**Comment by rik** [comment] 2022-11-11 10:51
This could be a Chrome bug. What version of Chrome are you seeing this on?

https://github.com/WPO-Foundation/webpagetest/issues/2519 is another Chrome/blending issue.

**Comment by kevinfarrugia** [comment] 2022-11-11 11:30
Currently on 107.0.5304.87 (Official Build) (64-bit) but the issue was also present on older versions.

109.0.5410.0 (Official Build) unknown (64-bit) still has this issue.

**Comment by stoyan** [comment] 2022-11-17 18:09
Thanks for the report and the proposed fix, closing as duplicate of earlier #2452

**Closed by stoyan** 2022-11-17 18:09 UTC
Labels: Type: Bug
