### ISSUE TITLE
Multi-page flows broken in Firefox when SPDY is enabled

### ISSUE THREAD

**Issue by jklein** [WPO-Foundation/webpagetest#145] opened 2013-11-05 22:10 UTC
I ran this script:

```
logData	0
navigate	https://velocity.jkle.in/testwpt/one.html
logData	1
navigate	https://velocity.jkle.in/testwpt/two.html
```

The results only have one HTTP request, plus N/A for all grades:

http://www.webpagetest.org/result/131105_0W_15ZD/

Compare to Chrome with the same script:

http://www.webpagetest.org/result/131105_AF_1613/1/details/

Compare to Firefox once I disabled SPDY:

http://www.webpagetest.org/result/131105_H3_1638/

Chrome and Firefox minus SPDY download the incremental CSS file and image that are on two.html.  

Server info:

nginx 1.4.3
SPDY v2

Let me know if I can provide more details!  I was trying to use this to test prefetching in Firefox, but this bug makes it impossible (as long as SPDY is on).

**Comment by nemobis** [comment] 2015-03-26 09:01
Another duplicate of https://github.com/WPO-Foundation/webpagetest/issues/20 ?

**Comment by andydavies** [comment] 2016-02-15 20:10
@pmeenan - given SPDY's demise and WPT's support for H2 in FF, guess this could probably be closed as won't fix?

**Comment by pmeenan** [comment] 2016-02-22 14:05
Good point.  Closing.  I had considered adding spdylay for the few edge cases where sites support SPDY but not H2 and where Firefox still supports SPDY but it's probably not worth the complexity or effort at this point.

**Closed by pmeenan** 2016-02-22 14:05 UTC
