### ISSUE TITLE
Multiple callbacks with tests sharded across agents 

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#798] opened 2017-01-25 22:16 UTC
It looks like the URL callback is pinged multiple times when using test sharding across agents.

Here's the job.log for a test.

```
UTC
2017/01/25 18:01:49 - Test Created
2017/01/25 18:25:23 - Starting test (initiated by tester i-0f5ffb38dfe9536b9)
2017/01/25 18:25:23 - Run 1 assigned to i-0f5ffb38dfe9536b9
2017/01/25 18:25:23 - Run 2 assigned to i-0c68babb36ba7b6dc
2017/01/25 18:25:23 - Run 3 assigned to i-01dec2dd48ddd656d
2017/01/25 18:25:55 - Test Run Complete. Run: 3, Cached: 0, Done: , Tester: i-01dec2dd48ddd656d
2017/01/25 18:25:55 - Test Run Complete. Run: 1, Cached: 0, Done: , Tester: i-0f5ffb38dfe9536b9
2017/01/25 18:25:55 - Test Run Complete. Run: 3, Cached: 0, Done: 1, Tester: i-01dec2dd48ddd656d
2017/01/25 18:25:55 - Test Run Complete. Run: 2, Cached: 0, Done: , Tester: i-0c68babb36ba7b6dc
2017/01/25 18:25:56 - Test Run Complete. Run: 1, Cached: 0, Done: 1, Tester: i-0f5ffb38dfe9536b9
2017/01/25 18:25:56 - Test Complete
2017/01/25 18:25:56 - Test Complete
2017/01/25 18:25:56 - Test Run Complete. Run: 2, Cached: 0, Done: 1, Tester: i-0c68babb36ba7b6dc
2017/01/25 18:25:57 - Test Complete
```

and here's the HTTP requests arriving at the callback.

```
NZDT
[26/Jan/2017:07:25:57 +1300] "GET /callback.php?id=xxx HTTP/1.1" 200 6919 "-" "-"
[26/Jan/2017:07:25:57 +1300] "GET /callback.php?id=xxx HTTP/1.1" 200 8390 "-" "-"
[26/Jan/2017:07:25:58 +1300] "GET /callback.php?id=xxx HTTP/1.1" 200 6887 "-" "-"
```

**Comment by pmeenan** [comment] 2017-01-26 16:57
Current guess is that the test locking that is supposed to happen in workdone to prevent concurrent processing isn't happening correctly (which would be bad) since it shows all 3 results coming in within the same 1 second interval.  I'm adding more logging to see if I can reproduce it and see if that really is the case.

**Comment by pmeenan** [comment] 2017-01-26 18:09
[This change](https://github.com/WPO-Foundation/webpagetest/commit/312f7fc01620f5c0fd73dd0e2f2612384203e455) MAY fix it though it's hard to say since I couldn't get it to reproduce (assume it is intermittent).  

If you pick up the [enhanced logging in workdone](https://github.com/WPO-Foundation/webpagetest/commit/361c8d6f4963835591634950328e00145edeab48) it might help narrow down the issue.

**Comment by zeman** [comment] 2017-01-27 00:27
The change to the locking seems to have done the trick.

Before deploying we were getting logs like this with two "Test post-processing complete"

```
2017/01/26 15:00:04 - Test Created
2017/01/26 15:00:31 - Starting test (initiated by tester i-0e3607b69a4706a4c)
2017/01/26 15:00:31 - Run 1 assigned to i-0e3607b69a4706a4c
2017/01/26 15:00:32 - Run 2 assigned to i-0c529d3a793a23269
2017/01/26 15:00:34 - Run 3 assigned to i-00115b07db4284807
2017/01/26 15:00:58 - Test Run Complete. Run: 1, Cached: 0, Done: , Tester: i-0e3607b69a4706a4c
2017/01/26 15:00:58 - Test Run Complete. Run: 2, Cached: 0, Done: , Tester: i-0c529d3a793a23269
2017/01/26 15:00:59 - Test Run Complete. Run: 3, Cached: 0, Done: , Tester: i-00115b07db4284807
2017/01/26 15:01:01 - Test Run Complete. Run: 1, Cached: 0, Done: 1, Tester: i-0e3607b69a4706a4c
2017/01/26 15:01:02 - Test Run Complete. Run: 3, Cached: 0, Done: 1, Tester: i-00115b07db4284807
2017/01/26 15:01:04 - Test Run Complete. Run: 2, Cached: 0, Done: 1, Tester: i-0c529d3a793a23269
2017/01/26 15:01:05 - Test Complete
2017/01/26 15:01:07 - Test Complete
2017/01/26 15:01:17 - Test post-processing complete
2017/01/26 15:01:18 - Test post-processing complete
```

After the change to locking we're just getting the one post-processing and callback.

```
2017/01/27 00:20:02 - Test Created
2017/01/27 00:20:54 - Starting test (initiated by tester i-03d67865a6109440d)
2017/01/27 00:20:54 - Run 1 assigned to i-03d67865a6109440d
2017/01/27 00:21:21 - Run 2 assigned to i-033d61e86b1658f96
2017/01/27 00:21:22 - Run 3 assigned to i-0726b49f5a16b6e85
2017/01/27 00:21:24 - Test Run Complete. Run: 1, Cached: 0, Done: , Tester: i-03d67865a6109440d
2017/01/27 00:21:24 - Done Processing. Run: 1, Cached: 0, Done: , Tester: i-03d67865a6109440d
2017/01/27 00:21:24 - Test Run Complete. Run: 1, Cached: 0, Done: 1, Tester: i-03d67865a6109440d
2017/01/27 00:21:24 - Done Processing. Run: 1, Cached: 0, Done: , Tester: i-03d67865a6109440d
2017/01/27 00:21:51 - Test Run Complete. Run: 3, Cached: 0, Done: , Tester: i-0726b49f5a16b6e85
2017/01/27 00:21:51 - Done Processing. Run: 3, Cached: 0, Done: , Tester: i-0726b49f5a16b6e85
2017/01/27 00:21:52 - Test Run Complete. Run: 3, Cached: 0, Done: 1, Tester: i-0726b49f5a16b6e85
2017/01/27 00:21:52 - Done Processing. Run: 3, Cached: 0, Done: , Tester: i-0726b49f5a16b6e85
2017/01/27 00:21:53 - Test Run Complete. Run: 2, Cached: 0, Done: , Tester: i-033d61e86b1658f96
2017/01/27 00:21:54 - Done Processing. Run: 2, Cached: 0, Done: , Tester: i-033d61e86b1658f96
2017/01/27 00:21:54 - Test Run Complete. Run: 2, Cached: 0, Done: 1, Tester: i-033d61e86b1658f96
2017/01/27 00:21:54 - Done Processing. Run: 2, Cached: 0, Done: 1, Tester: i-033d61e86b1658f96
2017/01/27 00:21:54 - Test Complete
2017/01/27 00:21:55 - Test post-processing complete
```

**Comment by zeman** [comment] 2017-01-29 22:02
Hmm... turns out I was a bit optimistic and we're still getting duplicate callbacks. Here's a log with the extra detail.

```
2017/01/29 21:00:39 - Test Created
2017/01/29 21:32:56 - Starting test (initiated by tester i-09bd0a94428d81d46)
2017/01/29 21:32:56 - Run 1 assigned to i-09bd0a94428d81d46
2017/01/29 21:32:56 - Run 2 assigned to i-0d47aefaa45537a7f
2017/01/29 21:32:58 - Run 3 assigned to i-053b3e7b2303f202f
2017/01/29 21:32:58 - Run 4 assigned to i-0782b880f64f6bc3c
2017/01/29 21:32:58 - Run 5 assigned to i-0ad925169ae39f94d
2017/01/29 21:33:11 - Test Run Complete. Run: 1, Cached: 0, Done: , Tester: i-09bd0a94428d81d46
2017/01/29 21:33:11 - Done Processing. Run: 1, Cached: 0, Done: , Tester: i-09bd0a94428d81d46
2017/01/29 21:33:11 - Test Run Complete. Run: 1, Cached: 0, Done: 1, Tester: i-09bd0a94428d81d46
2017/01/29 21:33:11 - Done Processing. Run: 1, Cached: 0, Done: , Tester: i-09bd0a94428d81d46
2017/01/29 21:33:11 - Test Run Complete. Run: 2, Cached: 0, Done: , Tester: i-0d47aefaa45537a7f
2017/01/29 21:33:11 - Done Processing. Run: 2, Cached: 0, Done: , Tester: i-0d47aefaa45537a7f
2017/01/29 21:33:11 - Test Run Complete. Run: 2, Cached: 0, Done: 1, Tester: i-0d47aefaa45537a7f
2017/01/29 21:33:11 - Done Processing. Run: 2, Cached: 0, Done: , Tester: i-0d47aefaa45537a7f
2017/01/29 21:33:12 - Test Run Complete. Run: 3, Cached: 0, Done: , Tester: i-053b3e7b2303f202f
2017/01/29 21:33:13 - Done Processing. Run: 3, Cached: 0, Done: , Tester: i-053b3e7b2303f202f
2017/01/29 21:33:13 - Test Run Complete. Run: 3, Cached: 0, Done: 1, Tester: i-053b3e7b2303f202f
2017/01/29 21:33:13 - Done Processing. Run: 3, Cached: 0, Done: , Tester: i-053b3e7b2303f202f
2017/01/29 21:33:13 - Test Run Complete. Run: 5, Cached: 0, Done: , Tester: i-0ad925169ae39f94d
2017/01/29 21:33:13 - Done Processing. Run: 5, Cached: 0, Done: , Tester: i-0ad925169ae39f94d
2017/01/29 21:33:13 - Test Run Complete. Run: 4, Cached: 0, Done: , Tester: i-0782b880f64f6bc3c
2017/01/29 21:33:13 - Done Processing. Run: 4, Cached: 0, Done: , Tester: i-0782b880f64f6bc3c
2017/01/29 21:33:13 - Test Run Complete. Run: 5, Cached: 0, Done: 1, Tester: i-0ad925169ae39f94d
2017/01/29 21:33:13 - Done Processing. Run: 5, Cached: 0, Done: 1, Tester: i-0ad925169ae39f94d
2017/01/29 21:33:13 - Test Complete
2017/01/29 21:33:13 - Test Run Complete. Run: 4, Cached: 0, Done: 1, Tester: i-0782b880f64f6bc3c
2017/01/29 21:33:13 - Done Processing. Run: 4, Cached: 0, Done: 1, Tester: i-0782b880f64f6bc3c
2017/01/29 21:33:13 - Test Complete
2017/01/29 21:33:15 - Test post-processing complete
2017/01/29 21:33:15 - Test post-processing complete
```

**Comment by pmeenan** [comment] 2017-02-06 15:30
Thanks, I think I have it figured out now.  Apparently the agent calls workdone for each run and then again when the full test is complete.  The individual runs are marked as being finished on the first call and then the final processing is done on the "done" call.

In the sharded case above, Run 4 sent the data which marked the run as complete and then run 5 sent the "done" message at which point it went through the list and all runs were marked as complete.  run 4's "done" message came after which then did the same thing again.

I think the correct fix for this will be to fix the agent to not always call workdone twice and instead pass the done flag on the actual data transfer.  That will also cut the request volume in half for posting results back.  Looking now to see how involved it will be.

**Comment by pmeenan** [comment] 2017-02-06 16:02
The server-side fix above will fix the issue by tracking the shard status separately from each test run.  That said, there will also be an updated agent shortly that eliminates the duplicate calls entirely.

**Comment by pmeenan** [comment] 2017-02-06 19:27
I just released wptdriver 358 which eliminates the duplicate calls on the agent side as well.  I'm fairly certain that either fix will fix it (though I recommend both).  Feel free to re-open the issue if you see it pop up again.

**Comment by pmeenan** [comment] 2017-02-06 19:31
Argh, don't pick up the workdone fix yet.  I'm seeing cases where it isn't working correctly.

**Comment by pmeenan** [comment] 2017-02-06 19:49
OK, Really fixed now.  The workdone fix earlier had picked a name for the shard tracking that collided with something set elsewhere.  Used a new name and it is working as expected (and live on the public WPT now).

**Comment by pmeenan** [comment] 2017-02-06 19:55
I don't have enough curse words....Not sure what's going on but something is somehow setting all of the bits to "true".

**Comment by pmeenan** [comment] 2017-02-06 20:16
OK, Fix stuck this time.  If you allow for re-running tests through the UI you'll also want the runtest.php fix.  The state of each shard was being carried forward from the previous test - ugh

**Closed by pmeenan** 2017-02-06 20:16 UTC
