### ISSUE TITLE
block URL not working on Service Worker URL network request

### ISSUE THREAD

**Issue by gilbertococchi** [WPO-Foundation/webpagetest#1305] opened 2019-10-15 08:37 UTC
Script Example with both absolute and rel URL:
```
block	https://sport.virgilio.it/sw.js sw.js
navigate	       https://sport.virgilio.it
```

https://webpagetest.org/result/191015_EC_e890a216a9f2e5e119acf1806769d951/1/details/#waterfall_view_step1

Expected result: sw.js to be blocked

Actual result: sw.js is not blocked and triggered correctly.
![Screenshot 2019-10-15 at 10 36 56](https://user-images.githubusercontent.com/329023/66814984-cb073e00-ef37-11e9-9aef-edc742a9d5da.png)

**Comment by rockeynebhwani** [comment] 2019-10-19 23:13
@gilbertococchi  - Looks like this is duplicate of https://github.com/WPO-Foundation/webpagetest/issues/1228

**Closed** 2020-03-18 09:09 UTC
