### ISSUE TITLE
Invalid UTF-8 in HAR output

### ISSUE THREAD

**Issue by acdha** [WPO-Foundation/webpagetest#436] opened 2015-05-06 19:31 UTC
I noticed that the HAR files cannot reliably be assumed to contain valid JSON, which assumes a UTF-8 character set. For example, a test for http://www.wdl.org/es/item/10623/ will produce a response which is invalid starting at the point where the Spanish page title is encoded in the file:

```
curl -s --no-remote-name-all 'http://www.webpagetest.org/export.php?bodies=1&pretty=1&test=150506_FT_139P' | python -m json.tool
'utf8' codec can't decode byte 0xfa in position 82: invalid start byte
```

**Comment by adamcath** [comment] 2015-07-31 18:18
We have determined at least one root cause of this. When WPT exports the query parameters for a given request, it url-decodes it, puts it in an in-memory data structure, and then exports to JSON.

Seems fine, right? Sadly, it's not fine. This process implicitly assumes that each query parameter is a percent-encoded stream of UTF-8 code units. But there's nothing in the URL spec or implementations that requires that percent-encoded characters in a URL correspond to any particular encoding; a URL is actually a stream of ascii characters and arbitrary percent-encoded bytes. The assumption is invalid.

PHP is perfectly happy to urldecode a bunch of arbitrary bytes into a string. Note that a PHP string is a sequence of bytes, _not_ a sequence of Unicode characters. A PHP string may or may not happen to be a valid UTF-8 string. But JSON has to be UTF-8, so exporting to JSON can fail if your PHP strings are not UTF-8.

Previously, WPT would indeed fail to export the HAR and instead produce a zero-byte response. But https://github.com/WPO-Foundation/webpagetest/commit/553e7340404b7917b9ba11f4c225bdb09739aa61 added a fallback to a "tolerant" (broken) user-space JSON library which is perfectly willing to emit JSON which has invalid UTF-8 sequences in it.

This should be fixed as follows (we will be sending a PR shortly):

1. Whenever WPT does URL decoding, check if the decoded string is valid UTF-8. If not, throw out the urldecoded version and keep the urlencoded version, in ASCII, percents and all.
2. Optionally, revert https://github.com/WPO-Foundation/webpagetest/commit/553e7340404b7917b9ba11f4c225bdb09739aa61 and add proper error handling instead. This could either just emit an error like "oops, I accidentally corrupted my internal data structure", or to be really tolerant, percent-encode any string that is not valid UTF-8, on the assumption that we missed something in (1).

**Closed** 2015-09-09 14:39 UTC
