### ISSUE TITLE
SPDY resources invisible for Firefox in the waterfall

### ISSUE THREAD

**Issue by jpvincent** [WPO-Foundation/webpagetest#411] opened 2015-03-09 13:27 UTC
I noticed on my private instance, and on the WPT.org too that resources served with SPDY that are located on the main domain do not appear on the waterfall.
It concerns only firefox, IE11 and chrome waterfalls, You can compare the twitter.com (SPDY enabled) page, from Fx, Chrome and IE 11 : 
http://www.webpagetest.org/video/compare.php?tests=150309_YP_NSQ,150309_AS_NRV,150309_NZ_NXW

Only the waterfall's Firefox does not display the twitter.com/ resource

**Comment by pmeenan** [comment] 2015-03-09 14:52
Dupe of Issue #20 - Hoping to get time to implement it this week or next (though I'll probably skip SPDY and only support HTTP/2 since SPDY is now depricated and HTTP/2 is final).

**Closed by pmeenan** 2015-03-09 14:52 UTC

**Comment by nemobis** [comment] 2015-03-26 08:57
Recent example with wikimedia.org: http://www.webpagetest.org/result/150326_17_BDV/
Are the timings wrong as well? They're very different in Chrome. http://www.webpagetest.org/result/150326_7Y_BDK/
