### ISSUE TITLE
Chrome 64 - ssl3_read_app_data error 0xc0000005

### ISSUE THREAD

**Issue by george-clement** [WPO-Foundation/webpagetest#1095] opened 2018-01-26 23:53 UTC
We are trying to deploy your solution into our work environment with chrome version 64. We are experiencing problems with ssl3_read_app_data not found. How to solve this issue? What is ssl3_read_app_data?

*Edit*

I just talk to our engineers and they say, in chrome PDB file ssl3_read_app_data and ssl3_connect its not there in latest version. I not know if this help!

**Comment by pmeenan** [comment] 2018-01-27 01:40
Is it crashing (pretty sure that's what 0xc000005 is)?  Those are the ssl functions that the legacy agent hooks to inspect traffic and it looks like it needs to be updated.  I may not get it fixed before Tuesday though depending on how involved the fix is.

FWIW, wptdriver is deprecated and it's highly recommended to move to [wptagent](https://github.com/WPO-Foundation/wptagent), specially if you are setting up a new instance.  wptagent is cross-platform and can run on Linux, Windows or Mac hosts and doesn't rely on code injection which will be breaking with Chrome permanently in a couple of months.

**Comment by george-clement** [comment] 2018-01-27 02:08
Yes, it is crashing. Our partners have used wptdriver for several years. We can expect a fix for this by Tuesday? Thank-you for the updates, and your great work!

**Comment by pmeenan** [comment] 2018-01-27 02:14
Tuesday at the latest. If I have a bit of downtime over the weekend it will be fixed before then.

________________________________

**Comment by pmeenan** [comment] 2018-01-27 15:59
What version of wptdriver were you using?  I couldn't reproduce it with 402 which should just skip the hooks it can't find.  To be safe, I just disable TLS hooking for Chrome 64 or later in wptdriver 403.  The results should still be good but some functionality will be missing for https requests (anything that needs the response body):

* Image compression and text compression optimization checks
* HTTP/2 request details
* Service worker requests will be missing
* Storing response bodies

In case you don't have it, the instructions for getting the latest agent are [here](https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/wptdriver.md#updating-test-agents).

All that said, I recommend starting to plan to move your partners to wptagent because wptdriver is going to completely break by June if Chrome's anti-injection plans don't change.

**Closed** 2018-01-27 15:59 UTC
