### ISSUE TITLE
Highlight the LCP image with a different colour highlight 

### ISSUE THREAD

**Issue by ebizindia** [WPO-Foundation/webpagetest#2071] opened 2022-06-24 03:23 UTC
## Feature Request Summary
Highlight the LCP image in a different color in the main waterfall (say green background like when we click on the LCP link).

### What's the motivation or use case for the change/feature?
Due to CWV concerns, we are always checking which resource is reported as the LCP and have to click the LCP link to find out. It should be easy to just apply a background color to the row of this element.

This will also make it clear how late this element is loaded and if that is quite late, the developer can plan to bring it up in the order.

**Comment by ebizindia** [comment] 2022-06-24 03:23
DebugBear does it in their waterfall.

**Comment by tkadlec** [comment] 2022-06-24 14:16
Dupe of #1804 so closing it here so discussion can happen there.

FWIW, I'm leaning towards this being a thing we do. :)

**Closed by tkadlec** 2022-06-24 14:16 UTC
Labels: Type: Enhancement

**Comment by tkadlec** [comment] 2022-06-24 14:36
Oh no worries! :) It happens (I've done it) and it's definitely not a big deal.
