### ISSUE TITLE
Endless test for mobile/4G after update

### ISSUE THREAD

**Issue by luizyamada** [WPO-Foundation/webpagetest#1419] opened 2021-01-04 19:58 UTC
After the code was updated, on December 18th, tests using the options of emulating mobile and using 4G network stopped working, where they start but never end (both by API and UI). 

When the test is performed without these two options (using the cable connection option), the test ends in less than 1 minute .
I tried to configure a server from zero and this problem still occurs. (both setups is in GCP)

I return the code to commit 2221de8c7999fc414ad082faee59748e7370c61d and it started to worked again.

There is any problem with these options in the last version of the code? 
Or, do i need to do anything else for this to work beyond what is described in this link?
https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/gce_server.md

Thanks

**Comment by pmeenan** [comment] 2021-01-05 15:33
Can you collect the debug output of the agent? That would help track down what is going wrong.  On GCP if you ssh as the "ubuntu" user you can attach to the screen session.

I can't think of anything that should be specific to 4G or mobile emulation and I can't reproduce the issue on the public instance so it's going to be hard to track down without logs. ([here](https://www.webpagetest.org/result/210105_DiFW_bda60a3a96f360e4c99f0c225acea888/) it is with GCE on the public instance)

**Comment by luizyamada** [comment] 2021-01-06 20:52
Sorry for my ignorance but, where i can check the debug output? 

Just to complement it, apparently, it’s not just 4G / mobile that’s causing problems but any testing (i created a new server / agents to try more tests without impact in the main vm's)

Trying the latest commits, the problem starts in this one 41324724310e80085b241da0dcc10bc9722914db
And i don't change anything in the agents vm's, only in the server vm

Do you have any tip to try to check if there is any problem with the communication between server / agent?

**Comment by pmeenan** [comment] 2021-01-07 15:48
My best guess is that the server is having problems with large file uploads. That change also got rid of sharding and it uploads a whole test result as a single zip instead of a post per run so the individual uploads will be bigger.

The php.ini settings of interest that come to mind:

upload_tmp_dir - in case you are uploading to /tmp and running out of ramdisk
upload_max_filesize
max_post_size

**Comment by pmeenan** [comment] 2021-01-11 15:54
Check your /install for the size of the php upload settings.  The file and post uploads should be well over 10MB to make sure it can handle really large tests with lots of video frames and response bodies (the public instance has it set at 100MB).

I'm closing this under the expectation that it's the upload size limit kicking in and a server config issue that the change exposed (have had a few other users with similar issues). Feel free to reopen it if you still see it happening after increasing the sizes in php.ini on your server.

**Closed by pmeenan** 2021-01-11 15:54 UTC
