### ISSUE TITLE
WebTestPage.org is not passing url querystrings

### ISSUE THREAD

**Issue by matthewDDennis** [WPO-Foundation/webpagetest#1363] opened 2020-06-10 21:51 UTC
I am trying to run a test against https://www.codeproject.com/Articles/5269455/Using-Cloud-AI-for-Sentiment-Analysis?display=Print but the waterfall shows requests that are not made when this parameter is present.  I've tried to URL encode the whole URL and just the queryString, but still no luck.

**Comment by pmeenan** [comment] 2020-06-11 13:03
Closing since the query string is passed correctly and the issue is server-side UA sniffing (which can be bypassed by preserving the original browser UA through settings).

**Closed by pmeenan** 2020-06-11 13:03 UTC

**Comment by matthewDDennis** [comment] 2020-06-11 20:57
I tried adding PST/123 to load this page and it worked correctly.  Given that there have been [other](https://www.webpagetest.org/forums/showthread.php?tid=14528&pid=28603#pid28603) complaints about dropped query string parameters, I think there is a bug somewhere.  I'm not a PHP programmer or I would try and find it.

**Comment by pmeenan** [comment] 2020-06-11 21:56
I don't know what to tell you, but it's pretty clear-cut.  Using the UA strings from the test with curl:

With PTST:
```
$ curl -s --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 PTST/200604.150630" https://www.codeproject.com/Articles/5269455/Using-Cloud-AI-for-Sentiment-Analysis?display=Print | head -15
```

```
<!DOCTYPE HTML>


<html lang="en">
<head>
	<title>Using Cloud AI for Sentiment Analysis - CodeProject</title>

	<link type="text/css" rel="stylesheet" href="https://www.codeproject.com/App_Themes/CodeProject/Css/Main.min.css?dt=2.8.200606.1">

    <script type="text/javascript" src="https://www.codeproject.com/script/JS/jquery-2.2.4.min.js" defer ></script>
<script type="text/javascript" src="https://www.codeproject.com/script/Articles/JS/article.min.js?dt=2.8.200606.1" defer ></script>
<script type="text/javascript" src="/script/Membership/JS/MemberProfilePopup.min.js?v=1.4" defer ></script>
<script type="text/javascript" src="/a.min.js?v=1.3"></script>

```

Without PTST:

```
$ curl -s --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" https://www.codeproject.com/Articles/5269455/Using-Cloud-AI-for-Sentiment-Analysis?display=Print | head -15
```

```
<!DOCTYPE HTML>


<html lang="en">
<head>
	<title>Using Cloud AI for Sentiment Analysis - CodeProject</title>

	<link type="text/css" rel="stylesheet" href="https://codeproject.freetls.fastly.net/App_Themes/CodeProject/Css/Main.min.css?dt=2.8.200606.1">

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" defer ></script>
<script type="text/javascript" src="https://codeproject.freetls.fastly.net/script/Articles/JS/article.min.js?dt=2.8.200606.1" defer ></script>
<script type="text/javascript" src="/script/Membership/JS/MemberProfilePopup.min.js?v=1.4" defer ></script>


<meta http-equiv="content-language" content="en-US">
```

Additionally, if the query params were getting dropped somewhere, they wouldn't show up in the netlog or the resulting waterfall.  In this case I am 100% confident that the query params are being passed correctly and that the server is UA sniffing and not handling the default UA addition (maybe because it's a dotted float, not an int after PTST).

**Comment by pmeenan** [comment] 2020-06-11 22:00
btw, the other complaint was because they were using the API and passing each option as a query param. i.e. http://www.webpagetest.org/runtest.php?url=http://www.example.com/?query=1

You can't pass form field data through query params without urlencoding it, otherwise you just break the request URL (a ? is an invalid character in the query part of the URL).

**Comment by matthewDDennis** [comment] 2020-06-11 22:56
I’ll try again with that user agent string
