### ISSUE TITLE
IE seems to be broken

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/webpagetest#771] opened 2016-12-02 15:15 UTC
Hi Patrick,
seems that latest work for edge broke measurements with internet explorer?
Just a simple url test with ie11:
https://www.webpagetest.org/result/161202_EG_T0Z/
Same with ie10:
https://www.webpagetest.org/result/161202_P1_T3J/
Regards, Nils

**Comment by nilskuhn** [comment] 2016-12-02 15:36
I've downgraded my agents to this build:
https://ci.appveyor.com/project/wptiteratec/webpagetest/build/2.19.184
Still doesn't work. Seems to be there for longer than a week.

**Comment by pmeenan** [comment] 2016-12-02 18:33
Yeah, not related to the Edge work - IE 11 looks to have broken in general.  It's on my list to look at but might not get to it until Monday

**Comment by RobCherry** [comment] 2016-12-02 18:56
IE 10 is also broken with the latest agent (2.19.0.337).

**Comment by pmeenan** [comment] 2016-12-02 20:07
Looking into it now.  Looks like it was probably when I added 64-bit support and was working on AppInit stuff.  It's reproducing in my dev VM so I should have a fix shortly.

**Comment by pmeenan** [comment] 2016-12-02 20:53
I stand corrected, it was 337-specific with the change to mongoose where keep-alive was enabled for the local web server.  The agent has never been sending content-length headers in the responses.  Packaging 338 up right now.

**Comment by pmeenan** [comment] 2016-12-02 21:00
338 is out now.

Leaving this open though because the pathological issue [was fixed](http://www.webpagetest.org/result/161202_P6_b17924b4d6e9da2410aeab9af530f0c7/) but something is [still broken](http://www.webpagetest.org/result/161202_63_2e203a3c56f7c91cea8caa8fd93d4976/) with IE 11 on a smattering of machines (like the Dulles Thinkpads) and has been for months.

**Comment by nilskuhn** [comment] 2016-12-05 12:32
Seems fixed to me, thanks.

**Comment by pmeenan** [comment] 2016-12-05 19:16
The remaining issue with IE is also fixed now.  There was an update that caused a modal prompt to select your home page and search provider (code was added to prevent it).

**Closed by pmeenan** 2016-12-05 19:16 UTC
