### ISSUE TITLE
WPTLoader fails with an Access Violation exception with Firefox 48

### ISSUE THREAD

**Issue by Etenil** [WPO-Foundation/webpagetest#724] opened 2016-09-26 13:31 UTC
When running a test on Firefox 48 with wptdriver 314 or the current master (8b9acd42b3b6b0db19597b37c213bce2f0499d44), wptload.dll fails at dllmain.cc:47 with an Access Violation exception; this is the place where the code attempts to read the user's name.

**Comment by pmeenan** [comment] 2016-09-26 17:02
I can't reproduce it here but either way it should be fixed with this: https://github.com/WPO-Foundation/webpagetest/commit/1f9c221d4623da8ffd4faf873b09c26fafd4866c

I'll roll out 315 in a little bit (have a few other things I want to get into it) and update when it is available.

**Closed** 2016-09-27 08:53 UTC

**Comment by pmeenan** [comment] 2016-09-28 21:35
I just pushed out the 315 build of wptdriver which includes the fix (if you want pre-built binaries)

**Comment by green-mdoerflinger** [comment] 2016-11-01 14:51
@pmeenan Where can i get the latest release? Are you planning on releasing a private instance package in the near future?

**Comment by pmeenan** [comment] 2016-11-01 15:19
The agents can [update independently of the web UI](https://sites.google.com/a/webpagetest.org/docs/private-instances#TOC-Updating-Test-Agents) and are released regularly.

The latest release of the web UI is pretty ancient at this point and I'll be cutting a new one in a few weeks.  I usually recommend to just run off of the tip of master which is what the public instance does which also makes it easy to sync updates.

**Comment by green-mdoerflinger** [comment] 2016-11-01 17:08
Thanks!
