### ISSUE TITLE
Scripts do not run on experiment

### ISSUE THREAD

**Issue by kevinfarrugia** [WPO-Foundation/webpagetest#1943] opened 2022-06-02 08:20 UTC
## Description
When adding a script to the test using the _Scripts_ tab, any experiments executed do not include the script. This is crucial for accepting GDPR cookie banners in the E.U. as well as many other use cases.

### Steps to reproduce
1. Create an Advanced Configuration
2. Under the Script tab, add your custom script. In the example below, I have added a simple script, but the same would happen for any script:
```
navigate	%url%?random=1
```
3. On the results screen, choose to run an experiment (any experiment will do).
4. Note how on the experiments (and control) tests, the script was not added.

### Expected result
The script should be added, so the document URL should include `?random=1`  (URL: https://webpagetest.org/themetrictimes/index.php?random=1).

### Actual result
The document URL for the control or experiment tests do not include `?random=1` (URL: https://experiments.webpagetest.org/themetrictimes/index.php).

### Test URLs
- Original: https://www.webpagetest.org/result/220602_AiDcDJ_6W5/
- Control: https://www.webpagetest.org/result/220602_AiDc7G_6YP/
- Experiment: https://www.webpagetest.org/result/220602_AiDcFW_6YQ/

**Comment by scottjehl** [comment] 2022-07-13 14:30
Agreed. Known limitation of experiments that we intend to improve! #2132 (Closing as dupe of broader issue)

**Closed by scottjehl** 2022-07-13 14:30 UTC
Labels: Type: Bug
