### ISSUE TITLE
TTFB problems on AWS

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/webpagetest#823] opened 2017-02-28 08:01 UTC
Hey Pat,
we have problems with TTFB on our our AWS agent but only when we log in a user or hit page and go to another (and only for Chrome). Maybe be should be two different issues, I can split them if that's the case.

# TTFB for logged users
We use a script to log in the user that looks like this:
<pre>
// The login page
logData 0
navigate https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page

// Log in the user
setValue        name=wpName     <%WPT_USER>
setValue        name=wpPassword <%WPT_USER_PASSWORD>
submitForm      name=userlogin

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	2

// This is the URL that we want to measure as a logged in user
logData 1
navigate https://en.wikipedia.org/wiki/Facebook
</pre>

And when we start a new agent, the TTFB looks ok, but after a while the TTFB gets really high but only for Chrome. If we kill the agent and start a new one, the TTFB goes back to normal (so it's something with that agent). The problem started I think November/December last year (but I didn't understand then that it was the agent that was the problem).
![ttfb](https://cloud.githubusercontent.com/assets/540757/23396623/f64d918c-fd94-11e6-981c-e3b8944f0c33.png)

The yellow line is Chrome, the green is Firefox. I've marked in the graph when we deploy a new agent (by killing it in AWS and the let WebPageTest spin up a new one). I understand this it probably not an WebPageTest/Chrome issue but it is a little strange that happens from Chrome and not Firefox? We keep the same agent up and running as long as possible, but maybe we should kill it once in a while?

# TTFB for second view
We have the same behavior but not abnormal TTFB for a script where we first hit one URL and then measure the next one:
<pre>
logData 0
navigate https://en.wikipedia.org/wiki/Main_Page

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	2

logData 1
navigate https://en.wikipedia.org/wiki/Barack_Obama
</pre>

And it looks like this for Chrome (Firefox is stable) (we had a problem with that script causing the missing data):
![newagent](https://cloud.githubusercontent.com/assets/540757/23396836/008ff03a-fd96-11e6-9d6e-a00d00b0e770.png)

Do you have any ideas? Or is the easiest fix to just redeploy new agents once in a while? Has anyone else seen the same problem?

Best
Peter

**Comment by pmeenan** [comment] 2017-02-28 13:25
There should be zero maintained state across tests so an agent degrading over time would be bad.  Do you happen to have waterfalls for the good and bad cases?  I'm wondering if there is some background activity of some kind that happens to get caught in the Chrome tests.

Another useful check would be to do a "combineSteps" version of the script on both Firefox and Chrome on one of the "bad" instances which should let you see the whole sequence.

**Comment by soulgalore** [comment] 2017-02-28 13:51
I'll add some waterfalls tonight, I should be able to dig up both bad and good examples. 

Ok, the next we get an "bad" agent again I'll run some combined steps. Thanks!

**Comment by soulgalore** [comment] 2017-02-28 20:21
Here's waterfall when it works as expected for Chrome:
http://wpt.wmftest.org/result/170228_5V_MV/

And here when it fails (yep the waterfalls looks strange and CPU is at top, didn't see when I looked a long time ago though):
http://wpt.wmftest.org/result/170226_QH_Q2/
And for Firefox (almost the same time same agent):
http://wpt.wmftest.org/result/170226_Y2_Q1/

**Comment by pmeenan** [comment] 2017-02-28 20:50
Other than the CPU load when it is doing the new connections, the main thing that jumps out is that the "slow" case is opening up new connections and TLS negotiations for en. and upload.  If you run with combine steps and enable netlog and can reproduce it that should give an indication of why the connection got closed (server-triggered or client).

My guess is that there is an idle timeout configured for the connections on the server and the tests are really close to that idle time between steps and for some reason the Chrome agents crossed over the timeout and Firefox didn't.

**Comment by soulgalore** [comment] 2017-03-10 11:27
Hi Pat, it has happened again and I've turned the netlog and added runs where combine the steps. It is the same thing as before, I can only see it for Chrome and TTFB goes high:

<img width="1234" alt="screen shot 2017-03-10 at 12 22 49 pm" src="https://cloud.githubusercontent.com/assets/540757/23793610/6610945c-058c-11e7-8f88-294e70bfec38.png">

Here's the regular runs with netlog turned on:
http://wpt.wmftest.org/result/170310_M8_B6/

And here netlog and combining the steps:
http://wpt.wmftest.org/result/170310_S2_B7/

They run on the same machine right after each others. And the combine script looks like this:
<pre>
// The login page
combineSteps
navigate https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page

// Log in the user
setValue        name=wpName     <%WPT_USER>
setValue        name=wpPassword <%WPT_USER_PASSWORD>
submitForm      name=userlogin

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	2

// This is the URL that we want to measure as a logged in user
navigate https://en.wikipedia.org/wiki/Facebook
</pre>

Any help or feedback is much appreciated :)

Best
Peter

**Comment by pmeenan** [comment] 2017-03-10 13:24
It looks like after ~5 seconds of inactivity, Chrome is closing the "idle" H2 connections (which is not great for H2 and I'll be opening an issue as soon as I can track it down).

From the "combined" waterfall, the gap between the log in and the new navigation just happens to be > 5 seconds (not sure why it grows over time though).

There is at least 2 seconds of waiting for no network activity as part of the normal navigation flow and then the 2 second sleep adds to it with a minimum of 4 seconds not including any other post-step work it is doing.

The short-term options that come to mind:
- Find a faster way to start with a blank page (cutting it down to 1 second might be enough but that might still cut it tight)
- Increase the sleep so it is always guaranteed to be over 5 seconds
- There is a "setABM" script command that can toggle WPT between "stop 1 second after onload" and "wait for 2 seconds of network activity" modes.  If you run the pre-measurements steps with setABM 0 and then setABM 1 before the last step it should have at least one second off of the gap as well

**Comment by pmeenan** [comment] 2017-03-10 13:26
btw, relevant bit in the netlog:

```
t= 8666 [st= 352]    HTTP2_STREAM_UPDATE_RECV_WINDOW
                     --> delta = 1542
                     --> window_size = 15728640
t=14969 [st=6655]    HTTP2_SESSION_CLOSE
                     --> description = "Closing idle sessions."
                     --> net_error = -3 (ERR_ABORTED)
```

I verified that the "Closing idle sessions." is a local action, not in response to a GOAWAY stream message.

**Comment by pmeenan** [comment] 2017-03-10 13:35
Opened a [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=700360) to track it on the Chrome side and so people who know a lot more about the socket pools than me can chime in.

**Comment by soulgalore** [comment] 2017-03-10 14:03
Cool, thanks! I'll test first to increase the wait time to be over 5 seconds and see what happens. 

Would it give any extra info if I kill the agent, deploy a new one and get the netlog again where the TTFB is low?

**Comment by pmeenan** [comment] 2017-03-10 14:13
I don't think it is time related.  In looking through the Chrome code, the only path that makes sense is one where Chrome purges memory (either because of memory pressure or for some other reason).  Still trying to track down the paths and conditions that would cause it to do that.

That might explain why it only happens after a while if something on the machines is using memory over time.  If you have a VM currently in that state that you can RDP into and check ResMon to see what the memory use looks like and what is consuming memory it might help

**Comment by pmeenan** [comment] 2017-03-10 14:22
And another update.... it may not be tied to overall system memory either (though that would explain the triggering over time).  Memory purging also triggers whenever the scheduler kicks in to slow down timers in a background tab/frame.  That shouldn't trigger in this case either but it looks like connections are closed way more aggressively than they should be.

**Comment by pmeenan** [comment] 2017-03-10 14:38
Keeping the "bad" agent in it's state is going to be the most useful.  If you can still reproduce it, a run that also includes a trace with the following trace categories might help:

renderer.scheduler,disabled-by-default-memory-infra

That would help track down which of the paths it is going down (if it is)

**Comment by soulgalore** [comment] 2017-03-10 14:40
Ok, cool. I've tested with 6s gap in the script and I think I get the same: http://wpt.wmftest.org/result/170310_X8_FM/
http://wpt.wmftest.org/result/170310_BE_FN/ (combined)

For 10s:
http://wpt.wmftest.org/result/170310_CF_FV/
http://wpt.wmftest.org/result/170310_4R_FW/ (combined)

With setAMB (still there compared to FF):
http://wpt.wmftest.org/result/170310_RN_FZ/
http://wpt.wmftest.org/result/170310_7G_FY/

I'll add the trace categories and test.

**Comment by soulgalore** [comment] 2017-03-10 14:45
Hmm I don't see a way to set the traceCategories through the API https://github.com/marcelduran/webpagetest-api (we have the web version turned off). Could I do it through a CLI switch?

**Comment by pmeenan** [comment] 2017-03-10 14:54
Argh.  It can be done through the API but it doesn't look like the wrapper supports it (yet anyway).

The API on the webpagetest side would be  traceCategories=renderer.scheduler,disabled-by-default-memory-infra

**Comment by soulgalore** [comment] 2017-03-10 15:02
I can probably do a PR for the wrapper this weekend and I'll keep the agent running.

**Comment by soulgalore** [comment] 2017-03-11 20:47
I've missed adding the trace categories this time (only did the PR). The thing is we where hit by the internet outage (or whatever happened) in US 2017-03-09 04:00 - 06:00 UTC. The measurements wasn't working for one hour but more interesting was that the overall TTFB metrics was 100 ms higher for 26 hours after that (I could see the same on my own test instance too, but that one is also located in the US). 

When that 100 ms went away, our WPT AWS agent TTFB went down to normal for authenticated users, so it seems that the extra slowdown make us hit that 5 s threshold.

**Comment by soulgalore** [comment] 2017-03-13 08:16
Fyi: I did the fix for the the wrapper API but it isn't working for me, so I did something wrong. Adding _renderer.scheduler,disabled-by-default-memory-infra_ via the web api works fine, but when I use the wrapper my tests times out: https://www.webpagetest.org/result/170313_A6_DV9/

Is this right?
<pre>
https://www.webpagetest.org/runtest.php?url=https%3A%2F%2Fwww.sitespeed.io&k=09d4f36ebc3a4bdfb05c9e8402b38524&trace=1&traceCategories=renderer.scheduler%2Cdisabled-by-default-memory-infra&f=json
</pre>

**Comment by soulgalore** [comment] 2017-03-29 07:45
This still looks to me that maybe have something 2do with the server/Windows/AWS? I run the same test with Chrome on Linux and don't get the same pattern (been running for 60 days). 

With our instance, it affects both our authenticated (log in a user and measure the next page) and second view (access one page fill the cache, measure the next page). Login users hits our origin servers. Others hit our caches. Looking at the last 60 days looks like this:

<img width="1266" alt="screen shot 2017-03-29 at 9 22 10 am" src="https://cloud.githubusercontent.com/assets/540757/24443521/414c1bc4-1463-11e7-9122-5008fcd8b0d7.png">

And every time I kill the agent and WPT deploys a new one, the metrics goes down?

**Comment by pmeenan** [comment] 2017-03-29 11:41
Do you have a non-login script (the second view script) that I can try on the public EC2 instances which have been running for close to a year?  If I can reproduce it I may be able to track down what is going on.

Also, if yours is currently in that state, any chance to collect the trace?

My current theory is that something on the machine is slowly leaking memory and it is triggering Chrome to trigger it's memory-critical flushing which closes the connections (though if I remember, the team didn't think that was enabled on Windows).  I am pretty sure it's not the agent itself since those get updated periodically and I haven't been able to reproduce the issue but it could be something in Windows itself (updates?) or some ec2-specific software in the VM's (if that's even the root cause).

**Comment by soulgalore** [comment] 2017-03-29 12:37
Yep sorry for not including it:
<pre>
logData 0
navigate https://en.wikipedia.org/wiki/Main_Page

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	1

logData 1
navigate https://en.wikipedia.org/wiki/Facebook
</pre>
We make 5 runs,  only do first run, collect the timeline and response bodies.

I tried different sleep time, but right now it's really short.

About the trace, yes but I wrote about it here: https://github.com/WPO-Foundation/webpagetest/issues/823#issuecomment-286040769 I've implemented it in the wrapper but it times out. Is the API call right that I added in that comment?

**Comment by soulgalore** [comment] 2017-03-29 12:50
And we use cable connectivity and see the same thing for our mobile tests running 3gfast.

**Comment by pmeenan** [comment] 2017-03-30 16:31
Unfortunately I couldn't reproduce it on any of the public locations so I'm still flying a little blind and guessing.  I'll take a look at the wrapper and see if I can reproduce the trace issue.

**Comment by soulgalore** [comment] 2017-03-31 07:31
I enabled the GUI for a short while to be able to pass on the categories. For the second view (where the change is smaller the 40 ms -> 100 ms) I got these (adding the two trace categories):
http://wpt.wmftest.org/result/170331_DP_8B/

But that change I think is because sometimes the first request does a "Initial Connection"
and "SSL Negotiation", sometimes not. 

The authenticated tests is back to normal since late 29th but I can do turn on the GUI again the next time it happens so we can collect the tracelog. 

Thanks for all the help looking into this!

**Comment by pmeenan** [comment] 2017-03-31 14:27
Yeah, the failure mode is because the initial request in the second step needs to re-establish the connection.  It does look like you can reproduce it but I expect the interesting stuff happens before the second step occurs.  Can you change the script to this:
```
combineSteps
navigate	https://en.wikipedia.org/wiki/Main_Page
exec document.body.innerHTML = "";
sleep	1
navigate	https://en.wikipedia.org/wiki/Facebook
```
That will let us capture the period where it decides to close the connections.

And re-run it with the following trace  categories (and also the netlog option):
```
netlog,toplevel,renderer.scheduler,disabled-by-default-memory_coordinator
```

There aren't a lot of trace paths around the memory pressure events but I think that should catch it if that is what is happening.

**Comment by soulgalore** [comment] 2017-03-31 14:57
I can fix that this weekend. But it is two different issues right, because when we have the problem with the authenticated it's more like an extra second?

**Comment by pmeenan** [comment] 2017-03-31 17:34
Part of it is the socket connect/TLS but the CPU is also pegged.  If it's related to running out of memory it could come back to the same root cause.  I don't see mention of it above, but what instance size are you running? m3.medium?

**Comment by soulgalore** [comment] 2017-03-31 17:58
Ok, we run a c3.large (following http://hostbenchmarker.com/blog/ec2-instance-type-used-webpagetest-agents/) but maybe we should change that? When we run on m3.medium our Firefox test failed really hard (we got gaps in the waterfall graphs when the CPU was totally busy).

**Comment by pmeenan** [comment] 2017-03-31 18:37
No, just wanted to be sure it wasn't something even smaller.  C3 (or C4) should be more than enough.

**Comment by soulgalore** [comment] 2017-08-29 05:01
Hi Pat, 
this has continued to happen now and then. We had a long (5 weeks) with nothing, but then it happened again (affecting Chrome/IE). I guess(?) this could be a Windows issue so if we move to Linux it would work (hopefully).

For the trace log to get more info, I think my change was merged in the WPT API but it isn't working see https://github.com/WPO-Foundation/webpagetest/issues/823#issuecomment-286040769  - is that the right way I call the API?

Best
Peter

**Comment by pmeenan** [comment] 2017-08-29 12:44
The API call looks fine as far as I can tell (minus the API key obviously).

**Closed** 2021-06-22 07:55 UTC
